class GameConstants:
    ROBOT_SIZE = [20, 20]
    OBSTACLE_SIZE = [40, 40]
    OBSTACLE_MOVING_SIZE = [20,20]
    GOAL_SIZE = [20,20]
    SCREEN_SIZE = [640, 480]



    ACTION_SPACE_SIZE = 8
    OBSERVATION_SPACE_VALUES = 800
    GOAL_REWARD = 6
    OBSTACLE_PENALTY = -2
    STEP_PENALTY = -0.01
    MAX_EPISODE_STEP = 200
    SPEED = 10
    SPEED_TEST = 5


    NUM_EPISODES = 40_000
    NUM_EPISODES_TEST = 202
    MINI_BATCH_SIZE = 64
    STEPS_PER_TARGET_UPDATE = 5
    REPLAY_MEMORY_SIZE = 50_000
    MIN_REPLAY_MEMORY_SIZE = 1_000
    NUM_SUCCESSFUL_EPS_TO_STOP = 20
    EPISODE_REPORT_COUNT = 100
    GAMMA = 0.95



